apiVersion: apps/v1
kind: Deployment
metadata:
  name: productservice
spec:
  replicas: 2
  selector:
    matchLabels:
      app: productservice
  template:
    metadata:
      labels:
        app: productservice
    spec:
      containers:
      - name: productservicedeploymentcontainer
        image: kubernetesproductdeployment
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
        env:
        - name: ConnectionStrings__DefaultConnection
          value: "Server=sqlserver,1433;Database=ProductDb;User Id=sa;Password=Deepak@123;TrustServerCertificate=True;"