trigger:
- main

pool:
  name: ProductServiceAgentPoolPractice
  demands:
  - Agent.Name -equals DeepakAgent

steps:

# Install .NET 10 SDK
- task: UseDotNet@2
  displayName: 'Install .NET 10 SDK'
  inputs:
    packageType: 'sdk'
    version: '10.x'

# Restore
- script: dotnet restore SRC/ProductService/ProductServicedeployment.csproj
  displayName: 'Restore API'

# Build
- script: dotnet build SRC/ProductService/ProductServicedeployment.csproj --configuration Release --no-restore
  displayName: 'Build API'

# Test
- script: dotnet test Test/ProductServiceTest/ProductServiceTest.csproj --configuration Release --no-restore
  displayName: 'Run Tests'

# Publish
- script: dotnet publish SRC/ProductService/ProductServicedeployment.csproj --configuration Release --output $(Build.ArtifactStagingDirectory)/publish --no-build
  displayName: 'Publish API'

# Create ZIP package
- task: ArchiveFiles@2
  displayName: 'Create Deployment Package'
  inputs:
    rootFolderOrFile: '$(Build.ArtifactStagingDirectory)/publish'
    includeRootFolder: false
    archiveType: 'zip'
    archiveFile: '$(Build.ArtifactStagingDirectory)/productservice.zip'
    replaceExistingArchive: true

# Deploy to Azure App Service
- task: AzureWebApp@1
  displayName: 'Deploy to Azure Web App'
  inputs:
    azureSubscription: 'AZServiceConnection'
    appType: 'webApp'
    appName: 'ProductService-Deepak'
    package: '$(Build.ArtifactStagingDirectory)/productservice.zip'
    deploymentMethod: 'zipDeploy'